### ISSUE TITLE
 How to monitor in background mode

### ISSUE THREAD

**Issue by smkumar84** [nraboy/ng-cordova-beacon#4]
Hi
Thanks for your code . I want to monitor the beacons in background mode. if possible scan the beacon in background mode. ? I have searched in Internet come many peoples are saying apple doesn’t allow the app in appastore for background mode app?
Please help me how to scan in background mode

**Comment by stephenrob** [comment]
I'm currently scanning for beacons in the background which allows me to show the user our app that's available when they are in range of our beacons, so they can easily open it from the lock screen on iOS.

I'm doing this using similar code to the following:

```
var beaconRegion = $cordovaBeacon.createBeaconRegion(identifier, uuid, major, minor, true);
$cordovaBeacon.startMonitoringForRegion(beaconRegion);
```

This will scan in the background for onEnterRegion and onExitRegion events and fire the following events so you can respond to them in your application if you need to do anything specifically.

```
'$cordovaBeacon:didEnterRegion'
'$cordovaBeacon:didExitRegion'
```

If you register a listener for these you can respond in your application to them.

```
$rootScope.$on('$cordovaBeacon:didEnterRegion', function(event, pluginResult) { });

$rootScope.$on('$cordovaBeacon:didExitRegion', function(event, pluginResult) { });
```

You also need to make sure you have requested the appropriate permissions from the user in order to either scan in the background for the beacons or only when the app is open.

`$cordovaBeacon.requestAlwaysAuthorization();`

This will request authorisation to always scan for beacons.

I've noticed that you also opened another issue on the underlying plugin this uses petermetz/cordova-plugin-ibeacon#240

**Comment by nraboy** [comment]
Thanks for jumping in @stephenrob!

**Comment by smkumar84** [comment]
Thanks @stephenrob Let me check then update you

**Comment by smkumar84** [comment]
@stephenrob i tried to call startMonitoringForRegion in background mode. But it is not wokring can you please advice where it is issue ?
